name: cell-line-signatures
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=3.6.2
  - bioconda-pyega3=3.1.0
  - r-devtools=2.3.2
  - r-tidyverse=1.3.0 
  - bioconductor-biobase=2.46.0
  - bioconductor-biocgenerics=0.32.0
  - r-data.table=1.12.8
  - bioconductor-genomicranges=1.38.0
  - bioconductor-yapsa=1.12.0
  - bioconductor-qdnaseq=1.22.0
  - r-foreach=1.5.0
  - r-domc=1.3.6
# - r-ASCAT=2.5.2 manually installed from repo
# - r-ASCAT.sc=1.0 manually installed from repo
