#!/bin/bash
#! Give your job a name
#SBATCH -J statjobsc
#! How many cores per task?
#SBATCH --cpus-per-task=1
#! How much memory do you need?
#SBATCH --mem=4G
#! How much wallclock time will be required?
#SBATCH --time=02:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL
#! Specify your email address here otherwise you won't recieve emails!
#SBATCH --mail-user=philip.smith@cruk.cam.ac.uk
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
#SBATCH --no-requeue
#! General partition
#SBATCH -p general
#SBATCH --output logs/slurm-%A.out
#SBATCH --error logs/slurm-%A.err
Rscript scripts/get_sc_ploidy_purity.R
